config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'users#new'

get '/login', to: 'user_sessions#new'
post '/login', to: 'user_sessions#create'
delete '/logout', to: 'user_sessions#destroy'


resources :users
resources :relationships, only: [:create, :destroy]

resources :posts, shallow: true do
  resources :comments
  resources :likes
  collection do
    get :like_posts
    get :search
  end
end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
    mount_uploaders :images, ImageUploader
    # 複数の画像を取り扱う場合、serializeメソッドが必要
    # JSON形式でなくとも、複数の画像を受け取ることは可能
    # ただ、posts_controllerにてJSON形式でデータを受け取るよう指定しているので、整合性を取る必要
    serialize :images, JSON
    validates :body, presence: true, length: { maximum: 1000 }
    validates :images, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    scope :feed_of, ->(user) { where(user_id: user.following_ids << user.id) }
    scope :body_contain, ->(word) { where('body LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index 
      @posts = if current_user
      current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
      else
        Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
      end
    end

    def search
      @posts = Post.body_contain(search_post_params[:body]).includes(:user).page(params[:page])
    end

    def new
        @post = Post.new
    end

    def create
      return redirect_to login_path unless current_user
        @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to posts_path, success: '投稿しました'
      else
        flash.now[:danger] = '投稿に失敗しました'
        render :new
      end
    end

    def edit
        @post = current_user.posts.find(params[:id])
    end

    def update
        @post = current_user.posts.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path, success: '投稿を更新しました'
      else
        flash.now[:danger] = '投稿の更新に失敗しました'
        reder :edit
      end
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments.includes(:user).order(created_at: :desc)
        @comment = Comment.new
    end

    def destroy
        @post = current_user.posts.find(params[:id])
        @post.destroy!
        redirect_to posts_path, success: '投稿を削除しました'
    end

    private

    def post_params
        # images:[]とすることで、JSON形式でparamsを受け取る
        params.require(:post).permit(:body, {images: []})
    end

    def search_post_params
      params.fetch(:q, {}).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|
  .form-group
    = f.label :images
    = f.file_field :images, multiple: true, class: 'form-control'
    /multiple: trueで複数選択可能に
    - post.images.each do |image|
      /image_tagを使うと、画像を簡単に配置できる
      /urlメソッドはcarrierwaveのメソッド
      /https://github.com/carrierwaveuploader/carrierwave#activerecord
      = image_tag image.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
= link_to post_likes_path(post), method: :post, remote: true do
  = icon 'far', 'heart', class: 'fa-lg'

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    = render 'unlike', post: post
  - else
    = render 'like', post: post

app/views/posts/_post.html.slim
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
     = link_to user_path(post.user) do 
      = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
      = post.user.name
      - if current_user&.own?(post)
        .ml-auto
          = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
      - if logged_in? && !current_user.own?(post)
        .ml-auto
          = render 'like_area', post: post  
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
      / せっかくなので、3D Flip Effectを試しに実装してみた
      / https://swiperjs.com/demos/#3D_flip_effect 
      .swiper-button-prev
      .swiper-button-next
  .card-body
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
= form_with model: search_form, url: search_posts_path, scope: :search, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  = f.search_field :body, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_unlike.html.slim
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/index.html.slim
.container 
 .row 
  .col-md-4.col-12 
    - if @posts.present?
     = render @posts
    - else 
     .text-center.font-weight-bold
          | 投稿がありません
    = paginate @posts
  .col-md-4.col-12 
   - if logged_in?
     .profile-box.md-3 
       = image_tag 'profile-placeholder.png', size: '50x50', class: 'rounded-circle mr-1'
       = current_user.name 
   .users-box 
    .card 
      .card-header 
       | ユーザー
      .card-body 
       = render User.recent(5)
      .card-footer 
        = link_to '全て見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            /image_tagを使うと、画像を簡単に配置できる
            /urlメソッドはcarrierwaveのメソッド
            /https://github.com/carrierwaveuploader/carrierwave#activerecord
            = image_tag image.url
      .swiper-pagination
      / せっかくなので、3D Flip Effectを試しに実装してみた
      / https://swiperjs.com/demos/#3D_flip_effect 
      .swiper-button-prev
      .swiper-button-next
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.name
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
    / hrで区切り線を引くことができる
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
       div id="comment-text"
       / コメント一覧
        = render 'comments/comment', comment: @comment
    hr.m-0
    .post-comment.p-3
      = render 'comments/form', post: @post, comment: @comment